spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/api/v1/users/(?<segment>.*), /api/v1/users/${segment}

        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/v1/coupons/**
          filters:
            - RewritePath=/api/v1/coupons/(?<segment>.*), /api/v1/coupons/${segment}

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/payments/**, /api/v1/reservations/**, /api/v1/reviews/**
          filters:
            - RewritePath=/api/v1/payments/(?<segment>.*), /api/v1/payments/${segment}
            - RewritePath=/api/v1/reservations/(?<segment>.*), /api/v1/reservations/${segment}
            - RewritePath=/api/v1/reviews/(?<segment>.*), /api/v1/reviews/${segment}

        - id: concert-service
          uri: lb://concert-service
          predicates:
            - Path=/api/v1/seats/**, /api/v1/venues/**, /api/v1/concerts/**
          filters:
            - RewritePath=/api/v1/seats/(?<segment>.*), /api/v1/seats/${segment}
            - RewritePath=/api/v1/venues/(?<segment>.*), /api/v1/venues/${segment}
            - RewritePath=/api/v1/concerts/(?<segment>.*), /api/v1/concerts/${segment}


jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

server:
  port: 8080

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, prometheus

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
    root: info
  config: classpath:logback-apigateway.xml