server:
  port: 8084

spring:
  application:
    name: coupon-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/couponservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  batch:
    jdbc:
      initialize-schema: never   # 수동으로 생성한 테이블과 충돌 방지
    job:
      enabled: false              # 애플리케이션 구동 시 자동 실행 방지
  sql:
    init:
      mode: never
      platform: mysql

  data:
    web:
      pageable:
        max-page-size: 500
        default-page-size: 500
    redis:
      host: localhost
      port: 6379

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update          # Hibernate가 스키마를 검증만 하고 변경하지 않도록 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        default_batch_fetch_size: 500

  kafka:
    bootstrap-servers: localhost:9092
    topic:
      coupon-events: coupon-events
      coupon-events-email: coupon-events-email
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    consumer:
      group-id: coupon-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.eatpizzaquickly.couponservice.event"
        fetch.min.bytes: 1024
        fetch.max.wait.ms: 500
        max.partition.fetch.bytes: 1048576
        enable.auto.commit: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
